from __future__ import print_function
import sys
import json
import argparse
import pprint 

from operator import itemgetter

import datetime
import pickle
import os.path
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request

# If modifying these scopes, delete the file token.pickle.
SCOPES = [
    'https://www.googleapis.com/auth/calendar' # Full calendar access is required to create the calendar from conference name
    ]
APPLICATION_NAME = 'Conference-Hall Google Agenda exporter'

SERVICE = None


pp = pprint.PrettyPrinter(indent=4)

def process_conference(conference_json_file):
    """Process conference file to generate the Google Agenda and the needed entries
    """
    with open(args.input, encoding='UTF-8') as file:
        conference = json.loads(file.read())
        conference_name = conference['name']
        calendar = get_or_create_calendar(conference_name)
        print("Using calendar %s" % calendar )
        formats = conference['formats']
        # TODO maybe filter talks to remove rejected ones prior to sort them
        talks = sorted(conference['talks'], key=itemgetter('rating'), reverse=True)
#        pp.pprint(talks)

def get_calendar_service():
    """
    Obtain the calendar service from Google
    """
    global SERVICE
    if SERVICE is None:
        print("No Google calendar service existing. Creating")
        creds = None
        # The file token.pickle stores the user's access and refresh tokens, and is
        # created automatically when the authorization flow completes for the first
        # time.
        if os.path.exists('token.pickle'):
            with open('token.pickle', 'rb') as token:
                creds = pickle.load(token)
        # If there are no (valid) credentials available, let the user log in.
        if not creds or not creds.valid:
            if creds and creds.expired and creds.refresh_token:
                creds.refresh(Request())
            else:
                flow = InstalledAppFlow.from_client_secrets_file(
                    'credentials.json', SCOPES)
                flow.user_agent = APPLICATION_NAME
                creds = flow.run_local_server()
            # Save the credentials for the next run
            with open('token.pickle', 'wb') as token:
                pickle.dump(creds, token)

        SERVICE = build('calendar', 'v3', credentials=creds)
        print("Google calendar service created")
    return SERVICE

def get_or_create_calendar(conference):
    """Create secondary calendar having as summary the given text
    """
    service = get_calendar_service()

    # This code is to fetch the calendar ids shared with me
    # Src: https://developers.google.com/google-apps/calendar/v3/reference/calendarList/list
    page_token = None
    while True:
        calendar_list = service.calendarList().list(pageToken=page_token).execute()
        for calendar_list_entry in calendar_list['items']:
            if calendar_list_entry['summary']==conference:
                print("calendar %s already exists! Retrieving it" % conference)
                return calendar_list_entry
        page_token = calendar_list.get('nextPageToken')
        if not page_token:
            break
    # Calendar not found. Creating !
    calendar = {
        'summary': conference,
        'timeZone': 'America/Los_Angeles'
    }
    print("calendar %s doesn't exist! Creating it" % conference)
    return service.calendars().insert(body=calendar).execute()


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description="A simple Python tool that fill a Google Calendar from a conference-hall export file"
    )
    parser.add_argument('--input',
        required = False,
        default = 'export.json',
        help = 'Export file generated by https://conference-hall.io for this conference')

    args = parser.parse_args()
    process_conference(args.input)
